### ISSUE TITLE
error when run

### ISSUE THREAD

**Issue by Mehran** [hakluke/hakrevdns#5] opened 2020-01-11 13:51 UTC
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4e8cc6]

goroutine 132 [running]:
net.(*Resolver).lookupAddr(0x0, 0x590ec0, 0xc42001a088, 0xc42001aad0, 0xc, 0x4297e9, 0x8, 0xc420058080, 0x0, 0xc4200eeef0)
        /usr/lib/go-1.10/src/net/lookup_unix.go:189 +0x26
net.(*Resolver).LookupAddr(0x0, 0x590ec0, 0xc42001a088, 0xc42001aad0, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/net/lookup.go:390 +0x5a
main.worker(0xc42001aad0, 0xc, 0xc42001a2e0, 0xc420064120)
        /root/go/src/github.com/hakluke/hakrevdns/main.go:35 +0xca
created by main.main
        /root/go/src/github.com/hakluke/hakrevdns/main.go:57 +0x17e

```

**Comment by hakluke** [comment] 2020-01-11 14:16
Hey @Mehran - what OS are you using, and what was the exact command you ran?

Ping @Alphakilo - it looks like it might be something to do with the custom resolver?

**Comment by Mehran** [comment] 2020-01-11 14:19
@hakluke im using ubuntu 18 , command i use 

```
prips iprange/24 | hakrevdns 
```

**Comment by Alphakilo** [comment] 2020-01-11 14:39
Yikes it does. ~~could you run
`prips iprange/24 | hakrevdns -r 1.1.1.1` 
as a reference?~~

Found the cause: Weirdly enough, when compiled with golang-1.13 it works as expected. Pretty sure the root cause is ec646e8bc4648d0fa3218cec63b26525d380a1be. 
@Mehran While I poke around a little more, would you be willing to [upgrade to golang-1.13](https://launchpad.net/~longsleep/+archive/ubuntu/golang-backports)?

**Comment by hakluke** [comment] 2020-01-13 01:15
Ah! Awesome, nice work @Alphakilo 

@Mehran would you mind trying the go update? If it works with the latest go then I'm happy to close this off. No need to support old go versions.

**Comment by BanhammersWrath** [comment] 2020-01-15 02:00
I had this same issue on Mint 19 their repo put golang 1.10 on my machine.  After upgrading to 1.13 the issue stopped happening and the app works as intended.

**Comment by hakluke** [comment] 2020-05-28 05:46
Cool :) Official fix: upgrade golang.

**Closed as completed by hakluke** 2020-05-28 05:46 UTC
